{
 "title": "Data Analysis Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": " Active Projects",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT COUNT(*) AS ActiveProjects\nFROM Projects\nWHERE Status = 'In Progress';",
     "rawQueryText": "SELECT COUNT(*) AS ActiveProjects\nFROM Projects\nWHERE Status = 'In Progress';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Project Success Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    (CAST(SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*)) * 100  AS ProjectSuccessRate\nFROM Projects;",
     "rawQueryText": "SELECT \n    (CAST(SUM(CASE WHEN Status = 'Completed' THEN 1 ELSE 0 END) AS FLOAT) / COUNT(*)) * 100  AS ProjectSuccessRate\nFROM Projects;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Total Revenue:",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT SUM(TotalValue) AS TotalRevenue\nFROM Projects;",
     "rawQueryText": "SELECT SUM(TotalValue) AS TotalRevenue\nFROM Projects;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average Project Value",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT AVG(TotalValue) AS AverageProjectValue\nFROM Projects;",
     "rawQueryText": "SELECT AVG(TotalValue) AS AverageProjectValue\nFROM Projects;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average Project Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT AVG(julianday(EndDate) - julianday(StartDate)) AS AverageProjectDuration\nFROM Projects;",
     "rawQueryText": "SELECT AVG(julianday(EndDate) - julianday(StartDate)) AS AverageProjectDuration\nFROM Projects;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Average Products per Projec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\nSELECT AVG(ProductCount) AS AvgProductsPerProject\nFROM (\n    SELECT ProjectID, COUNT(DISTINCT ProductID) AS ProductCount\n    FROM ProjectDetails\n    GROUP BY ProjectID\n);",
     "rawQueryText": "\nSELECT AVG(ProductCount) AS AvgProductsPerProject\nFROM (\n    SELECT ProjectID, COUNT(DISTINCT ProductID) AS ProductCount\n    FROM ProjectDetails\n    GROUP BY ProjectID\n);",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Monthly Revenue",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%Y-%m', StartDate) AS Month, \n    SUM(TotalValue) AS MonthlyRevenue\nFROM Projects\nGROUP BY Month\nORDER BY Month;",
     "rawQueryText": "SELECT \n    strftime('%Y-%m', StartDate) AS Month, \n    SUM(TotalValue) AS MonthlyRevenue\nFROM Projects\nGROUP BY Month\nORDER BY Month;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Category Revenue",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "queryText": "SELECT p.Category, SUM(pd.TotalPrice) AS CategoryRevenue\nFROM Products p\nJOIN ProjectDetails pd ON p.ProductID = pd.ProductID\nGROUP BY p.Category\nORDER BY CategoryRevenue DESC;",
     "rawQueryText": "SELECT p.Category, SUM(pd.TotalPrice) AS CategoryRevenue\nFROM Products p\nJOIN ProjectDetails pd ON p.ProductID = pd.ProductID\nGROUP BY p.Category\nORDER BY CategoryRevenue DESC;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Product Profitability",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT \n    p.ProductID, \n    p.ProductName,\n    SUM(pd.TotalPrice) AS TotalRevenue,\n    SUM(pd.Quantity * p.unitprice) AS TotalCost,\n    SUM(pd.TotalPrice) - SUM(pd.Quantity * p.unitprice) AS Profit,\n  (SUM(pd.TotalPrice) - SUM(pd.Quantity * p.unitprice)) / SUM(pd.TotalPrice) * 100 AS ProfitMargin\nFROM Products p\nLeft JOIN ProjectDetails pd ON p.ProductID = pd.ProductID\nGROUP BY p.ProductID, p.ProductName;",
     "rawQueryText": "SELECT \n    p.ProductID, \n    p.ProductName,\n    SUM(pd.TotalPrice) AS TotalRevenue,\n    SUM(pd.Quantity * p.unitprice) AS TotalCost,\n    SUM(pd.TotalPrice) - SUM(pd.Quantity * p.unitprice) AS Profit,\n  (SUM(pd.TotalPrice) - SUM(pd.Quantity * p.unitprice)) / SUM(pd.TotalPrice) * 100 AS ProfitMargin\nFROM Products p\nLeft JOIN ProjectDetails pd ON p.ProductID = pd.ProductID\nGROUP BY p.ProductID, p.ProductName;",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Project Completion Time Analysis:",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "queryText": "SELECT \n    ProjectID,\n    julianday(EndDate) - julianday(StartDate) AS ActualDurationindays,\n    CASE \n        WHEN julianday(EndDate) - julianday(StartDate) <= 30 THEN 'Short'\n        WHEN julianday(EndDate) - julianday(StartDate) <= 90 THEN 'Medium'\n        ELSE 'Long'\n    END AS DurationCategory\nFROM Projects\nWHERE Status = 'Completed';",
     "rawQueryText": "SELECT \n    ProjectID,\n    julianday(EndDate) - julianday(StartDate) AS ActualDurationindays,\n    CASE \n        WHEN julianday(EndDate) - julianday(StartDate) <= 30 THEN 'Short'\n        WHEN julianday(EndDate) - julianday(StartDate) <= 90 THEN 'Medium'\n        ELSE 'Long'\n    END AS DurationCategory\nFROM Projects\nWHERE Status = 'Completed';",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}